---
title: "neighbourhood analysis"
output: pdf_document
---


```{r}
library(readr)
library(ggplot2)
library(reshape2)

```

```{r}
neighbour_csvfolder <- "/Users/cope01/Documents/MATLAB/ImageAnalysis/neighbourhood_csv"
neighbour_csv_list <- list.files(neighbour_csvfolder, pattern = ".csv", recursive = T, full.names = T)
all_neighbour_files <- lapply(neighbour_csv_list, function (i) read.csv(i, header=FALSE))
#names(all_neighbour_files) <- sub("/Users/cope01/Documents/MATLAB/ImageAnalysis/neighbourhood_csv/", "", neighbour_csv_list)
#names(all_neighbour_files) <- sub("_neighbourhood.csv", "", names(all_neighbour_files))

#all_neighbour_files <-  lapply(all_files, transpose)
names <- names(all_neighbour_files)
```


```{r}
tumour_neighbours_15 <- data.frame(matrix(NA, ncol=17, nrow = 477))
colnames(tumour_neighbours_15) <- c("Image_ID","neighbour", "n1",  "n2" , "n3" , "n4" , "n5" , "n6",  "n7",  "n8",  "n9",  "n10", "n11" ,"n12" ,"n13" ,"n14", "n15")
for (i in 1:length(all_neighbour_files)){
  tmp_df <- data.frame(t(all_neighbour_files[[i]]))
  colnames(tmp_df) <- c("base_cell", "n1",  "n2" , "n3" , "n4" , "n5" , "n6",  "n7",  "n8",  "n9",  "n10", "n11" ,"n12" ,"n13" ,"n14", "n15")
  tmp_tumour <- tmp_df[which(tmp_df$base_cell==1),]
  tmp_lymphocyte <- tmp_df[which(tmp_df$base_cell==2), ]
  tmp_stroma <- tmp_df[which(tmp_df$base_cell==3), ]
  #total number of cells
  tmp_prop_t <- sum(tmp_df$base_cell==1)/nrow(tmp_df)
  tmp_prop_l <- sum(tmp_df$base_cell==2)/nrow(tmp_df)
  tmp_prop_s<- sum(tmp_df$base_cell==3)/nrow(tmp_df)
  #first column is image ID
  tumour_neighbours_15[(3*i-2):(3*i), 1] <- names(all_neighbour_files)[i]
  #second column is base_cell
  tumour_neighbours_15[(3*i-2):(3*i), 2] <- c("tumour", "lymphocyte", "stroma")
  #now the proportion adjusted to cell proportion
  for (j in 1:15){
  tumour_neighbours_15[(3*i-2), j+2] <- (sum(tmp_tumour[,j+1]==1)/nrow(tmp_tumour))/tmp_prop_t
  tumour_neighbours_15[(3*i-1), j+2] <- (sum(tmp_tumour[,j+1]==2)/nrow(tmp_tumour))/tmp_prop_l
  tumour_neighbours_15[(3*i), j+2] <- (sum(tmp_tumour[,j+1]==3)/nrow(tmp_tumour))/tmp_prop_s
  }
}


```

now using lymphocyte as a base and stromal cells as base

```{r}
lymph_neighbours_15 <- data.frame(matrix(NA, ncol=17, nrow = 477))
stroma_neighbours_15 <- data.frame(matrix(NA, ncol=17, nrow = 477))
colnames(lymph_neighbours_15) <- c("Image_ID","neighbour", "n1",  "n2" , "n3" , "n4" , "n5" , "n6",  "n7",  "n8",  "n9",  "n10", "n11" ,"n12" ,"n13" ,"n14", "n15")
colnames(stroma_neighbours_15) <- c("Image_ID","neighbour", "n1",  "n2" , "n3" , "n4" , "n5" , "n6",  "n7",  "n8",  "n9",  "n10", "n11" ,"n12" ,"n13" ,"n14", "n15")
for (i in 1:length(all_neighbour_files)){
  tmp_df <- data.frame(t(all_neighbour_files[[i]]))
  colnames(tmp_df) <- c("base_cell", "n1",  "n2" , "n3" , "n4" , "n5" , "n6",  "n7",  "n8",  "n9",  "n10", "n11" ,"n12" ,"n13" ,"n14", "n15")
  #tmp_tumour <- tmp_df[which(tmp_df$base_cell==1),]
  tmp_lymphocyte <- tmp_df[which(tmp_df$base_cell==2), ]
  tmp_stroma <- tmp_df[which(tmp_df$base_cell==3), ]
  #total number of cells
  tmp_prop_t <- sum(tmp_df$base_cell==1)/nrow(tmp_df)
  tmp_prop_l <- sum(tmp_df$base_cell==2)/nrow(tmp_df)
  tmp_prop_s<- sum(tmp_df$base_cell==3)/nrow(tmp_df)
  #first column is image ID
  tumour_neighbours_15[(3*i-2):(3*i), 1] <- names(all_neighbour_files)[i]
  for (i in 1:length(all_neighbour_files)){
  lymph_neighbours_15[(3*i-2):(3*i), 1] <- names(all_neighbour_files)[i]
  stroma_neighbours_15[(3*i-2):(3*i), 1] <- names(all_neighbour_files)[i]
    lymph_neighbours_15[(3*i-2):(3*i), 2] <- c("tumour", "lymphocyte", "stroma")
  stroma_neighbours_15[(3*i-2):(3*i), 2] <- c("tumour", "lymphocyte", "stroma")

  }
  #second column is neighbour
  tumour_neighbours_15[(3*i-2):(3*i), 2] <- c("tumour", "lymphocyte", "stroma")
  #now the proportion adjusted to cell proportion
  for (j in 1:15){
  tumour_neighbours_15[(3*i-2), j+2] <- (sum(tmp_tumour[,j+1]==1)/nrow(tmp_tumour))/tmp_prop_t
  tumour_neighbours_15[(3*i-1), j+2] <- (sum(tmp_tumour[,j+1]==2)/nrow(tmp_tumour))/tmp_prop_l
  tumour_neighbours_15[(3*i), j+2] <- (sum(tmp_tumour[,j+1]==3)/nrow(tmp_tumour))/tmp_prop_s
  
    lymph_neighbours_15[(3*i-2), j+2] <- (sum(tmp_lymphocyte[,j+1]==1)/nrow(tmp_lymphocyte))/tmp_prop_t
  lymph_neighbours_15[(3*i-1), j+2] <- (sum(tmp_lymphocyte[,j+1]==2)/nrow(tmp_lymphocyte))/tmp_prop_l
  lymph_neighbours_15[(3*i), j+2] <- (sum(tmp_lymphocyte[,j+1]==3)/nrow(tmp_lymphocyte))/tmp_prop_s
  
  stroma_neighbours_15[(3*i-2), j+2] <- (sum(tmp_stroma[,j+1]==1)/nrow(tmp_stroma))/tmp_prop_t
  stroma_neighbours_15[(3*i-1), j+2] <- (sum(tmp_stroma[,j+1]==2)/nrow(tmp_stroma))/tmp_prop_l
  stroma_neighbours_15[(3*i), j+2] <- (sum(tmp_stroma[,j+1]==3)/nrow(tmp_stroma))/tmp_prop_s
  }
  
 
  
  
  
  
  
  
}

```





now get the meta data

```{r}

#all base cell tumour in this chunk
tumour_neighbours_15_extra <- merge(tumour_neighbours_15, test_df_rcb, by="Image_ID")

neighbour_tumour <- tumour_neighbours_15_extra[which(tumour_neighbours_15_extra$neighbour=="tumour"), ]
neighbour_tumour_sub <- neighbour_tumour[, c(1:19, 80, 81, 83)]
neighbour_tumour_sub_melted <- melt(neighbour_tumour_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
neighbour_tumour_sub_melted$position <- as.numeric(sub("n", "", neighbour_tumour_sub_melted$variable))

ggplot(neighbour_tumour_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")



neighbour_lymph <- tumour_neighbours_15_extra[which(tumour_neighbours_15_extra$neighbour=="lymphocyte"), ]
neighbour_lymph_sub <- neighbour_lymph[, c(1:19, 80, 81, 83)]
neighbour_lymph_sub_melted <- melt(neighbour_lymph_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
neighbour_lymph_sub_melted$position <- as.numeric(sub("n", "", neighbour_lymph_sub_melted$variable))

ggplot(neighbour_lymph_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")

ggplot(neighbour_lymph_sub_melted[which(neighbour_lymph_sub_melted$value<50), ], aes(x=position, y=value, colour=pCR))+
  geom_smooth(method="lm")+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")







neighbour_stroma <- tumour_neighbours_15_extra[which(tumour_neighbours_15_extra$neighbour=="stroma"), ]
neighbour_stroma_sub <- neighbour_stroma[, c(1:19, 80, 81, 83)]
neighbour_stroma_sub_melted <- melt(neighbour_stroma_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
neighbour_stroma_sub_melted$position <- as.numeric(sub("n", "", neighbour_stroma_sub_melted$variable))

ggplot(neighbour_stroma_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")

```


now base cell lymph
```{r}
lymph_neighbours_15_extra <- merge(lymph_neighbours_15, test_df_rcb, by="Image_ID")
#bl=base cell lymph, nt=neighbour cell tumour

bl_nt <- lymph_neighbours_15_extra[which(lymph_neighbours_15_extra$neighbour=="tumour"), ]
bl_nt_sub <- bl_nt[, c(1:19, 80, 81, 83)]
bl_nt_sub_melted <- melt(bl_nt_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
bl_nt_sub_melted$position <- as.numeric(sub("n", "", bl_nt_sub_melted$variable))

ggplot(bl_nt_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")



bl_nl <- lymph_neighbours_15_extra[which(lymph_neighbours_15_extra$neighbour=="lymphocyte"), ]
bl_nl_sub <- bl_nl[, c(1:19, 80, 81, 83)]
bl_nl_sub_melted <- melt(bl_nl_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
bl_nl_sub_melted$position <- as.numeric(sub("n", "", bl_nl_sub_melted$variable))

ggplot(bl_nl_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")





bl_ns <- lymph_neighbours_15_extra[which(lymph_neighbours_15_extra$neighbour=="stroma"), ]
bl_ns_sub <- bl_ns[, c(1:19, 80, 81, 83)]
bl_ns_sub_melted <- melt(bl_ns_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
bl_ns_sub_melted$position <- as.numeric(sub("n", "", bl_ns_sub_melted$variable))

ggplot(bl_ns_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")


```


now base cell stroma

```{r}
stroma_neighbours_15_extra <- merge(stroma_neighbours_15, test_df_rcb, by="Image_ID")

bs_nt <- stroma_neighbours_15_extra[which(stroma_neighbours_15_extra$neighbour=="tumour"), ]
bs_nt_sub <- bs_nt[, c(1:19, 80, 81, 83)]
bs_nt_sub_melted <- melt(bs_nt_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
bs_nt_sub_melted$position <- as.numeric(sub("n", "", bs_nt_sub_melted$variable))

ggplot(bs_nt_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")


bs_nl <- stroma_neighbours_15_extra[which(stroma_neighbours_15_extra$neighbour=="lymphocyte"), ]
bs_nl_sub <- bs_nl[, c(1:19, 80, 81, 83)]
bs_nl_sub_melted <- melt(bs_nl_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
bs_nl_sub_melted$position <- as.numeric(sub("n", "", bs_nl_sub_melted$variable))

ggplot(bs_nl_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")





bs_ns <- stroma_neighbours_15_extra[which(stroma_neighbours_15_extra$neighbour=="stroma"), ]
bs_ns_sub <- bs_ns[, c(1:19, 80, 81, 83)]
bs_ns_sub_melted <- melt(bs_ns_sub, id.vars=c("Image_ID", "neighbour", "Trial_ID", "RCB", "pCR", "HER2_ER_status","lowmedhigh"))
bs_ns_sub_melted$position <- as.numeric(sub("n", "", bs_ns_sub_melted$variable))

ggplot(bs_ns_sub_melted, aes(x=position, y=value, colour=pCR))+
  geom_smooth()+
  theme_bw(base_size=30)+
  scale_x_discrete(limits=c(1:15))+
  theme(axis.text = element_text(face="bold"), legend.position = "none", axis.text.y = element_text(size = 34))+
  xlab("")+
  ylab("")




+
    
     scale_colour_discrete(name = "Response")+
  xlab("Position from the base stromal cell")+
  ylab("Normalised likelyhood")++
  labs(fill="Residual Tumour")+

```

